apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: shishe
  labels:
    app: shishe-keycloak
spec:
  selector:
    app: shishe-keycloak
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 31002
