apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: shishe
  labels:
    app: shishe-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shishe-keycloak
  template:
    metadata:
      labels:
        app: shishe-keycloak
    spec:
      containers:
      - name: keycloak
        image: jboss/keycloak
        resources:
          limits:
            memory: "512Mi"
            cpu: "1800m"
        ports:
        - containerPort: 8080
        env:
          - name: DB_ADDR
            valueFrom:
              configMapKeyRef:
                name: shishe-configmap
                key: keycloak_database_host
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: shishe-configmap
                key: keycloak_database_name
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: shishe-secret
                key: keycloak-database-user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: shishe-secret
                key: keycloak-database-password
          - name: DB_VENDOR
            value: postgres
