apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: shishe
  labels:
    app: shishe-pgAdmin
spec:
  selector:
    app: shishe-pgAdmin
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31001
