apiVersion: v1
kind: Service
metadata:
  name: postgresservice
  namespace: shishe
  labels:
    app: shishe-postgres
spec:
  selector:
    app: shishe-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
