apiVersion: v1
kind: Service
metadata:
  name: postgresservice
  namespace: shishe
  labels:
    app: shishe-postgres
spec:
  type: LoadBalancer
  selector:
    app: shishe-postgres
  ports:
  - port: 5432
    targetPort: 5432
